version: "3.9"

services:
    database:
        image: postgres
        container_name: database_ignite
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=rentx
        volumes:
            - pgdata:/data/postgres
        
    app:
        build: .
        container_name: rentx
        restart: always
        ports: 
        
            - 3333:3333
            - 9229:9229 # pra usar o debug
        volumes: 
            - .:/usr/app
        links: 
           - database
        depends_on:
            - database

volumes: 
    pgdata: 
        driver: local